##**Iris Data Prediction**

 **About Dataset**

It includes three iris species with 50 samples each as well as some properties about each flower. One flower species is linearly separable from the other two, but the other two are not linearly separable from each other.

The columns in this dataset are:

1. Id
2. SepalLengthCm
3. SepalWidthCm
4. PetalLengthCm
5. PetalWidthCm
6. Species

**Target**

To predict Flower Species

**Approach**:

Training using Artifical Neural Network

# **Importing Libraries**

In [1]:
import numpy as np 
import pandas as pd 

import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

import scipy as sp 
import sklearn
import random 
import time 


from keras.models import Sequential 
from keras.layers import Dense 
from keras.utils import np_utils
from sklearn.utils import shuffle
from sklearn.preprocessing import LabelEncoder
from keras.utils.np_utils import to_categorical
from sklearn import preprocessing, model_selection

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


# **Importing Data**

In [2]:
iris = pd.read_csv('/content/drive/My Drive/ML Projects datasets/Iris Prediction/Iris.csv')
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
#removing Id Column
iris = iris.drop(['Id'], axis =1)

In [4]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


# **Splitting data into X,Y and prediction**

We are going to separate the data. One part will be used to make predictions in the end, the other part, the most important will be used for training and testing the neural network. This part is not mandatory, but it is for fun, and especially to show how to predict from an input.

In [5]:
iris[:8]

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa
5            5.4           3.9            1.7           0.4  Iris-setosa
6            4.6           3.4            1.4           0.3  Iris-setosa
7            5.0           3.4            1.5           0.2  Iris-setosa

In [6]:
iris = shuffle(iris)
i = 8
data_to_predict = iris[:i].reset_index(drop = True)
predict_species = data_to_predict.Species 
predict_species = np.array(predict_species)
prediction = np.array(data_to_predict.drop(['Species'],axis= 1))

iris = iris[i:].reset_index(drop = True)

# X and Y for training the model
X = iris.drop(['Species'], axis = 1)
X = np.array(X)
Y = iris['Species']


In [7]:
#array of already labeled species
predict_species

array(['Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa'], dtype=object)

In [8]:
#array of features of species to be predicted
prediction

array([[5. , 3.2, 1.2, 0.2],
       [6.4, 3.1, 5.5, 1.8],
       [6.2, 2.9, 4.3, 1.3],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.2, 4.1, 1.5, 0.1],
       [6.4, 2.8, 5.6, 2.2],
       [4.4, 3.2, 1.3, 0.2]])

In [9]:
print(X)
print(Y)

[[5.8 2.7 5.1 1.9]
 [5.7 2.8 4.1 1.3]
 [5.  3.3 1.4 0.2]
 [6.2 2.2 4.5 1.5]
 [5.2 2.7 3.9 1.4]
 [5.6 2.8 4.9 2. ]
 [4.9 3.  1.4 0.2]
 [4.6 3.4 1.4 0.3]
 [5.6 3.  4.1 1.3]
 [7.7 3.  6.1 2.3]
 [6.6 3.  4.4 1.4]
 [6.4 3.2 5.3 2.3]
 [4.5 2.3 1.3 0.3]
 [6.  2.2 5.  1.5]
 [5.5 4.2 1.4 0.2]
 [6.3 2.5 5.  1.9]
 [6.1 2.8 4.7 1.2]
 [6.7 3.  5.2 2.3]
 [6.5 3.2 5.1 2. ]
 [4.8 3.1 1.6 0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.  1.4 0.1]
 [5.4 3.9 1.7 0.4]
 [5.7 2.5 5.  2. ]
 [5.1 3.5 1.4 0.3]
 [6.  2.9 4.5 1.5]
 [6.3 3.3 4.7 1.6]
 [5.9 3.  4.2 1.5]
 [5.1 3.5 1.4 0.2]
 [5.8 2.7 4.1 1. ]
 [6.8 3.2 5.9 2.3]
 [5.  3.4 1.5 0.2]
 [5.1 3.7 1.5 0.4]
 [6.7 3.1 4.4 1.4]
 [7.2 3.  5.8 1.6]
 [4.8 3.4 1.6 0.2]
 [6.4 2.8 5.6 2.1]
 [5.1 2.5 3.  1.1]
 [4.6 3.6 1.  0.2]
 [6.3 3.4 5.6 2.4]
 [4.4 2.9 1.4 0.2]
 [5.  3.5 1.6 0.6]
 [5.4 3.7 1.5 0.2]
 [5.1 3.4 1.5 0.2]
 [4.9 2.4 3.3 1. ]
 [4.4 3.  1.3 0.2]
 [7.2 3.6 6.1 2.5]
 [6.7 3.3 5.7 2.5]
 [7.4 2.8 6.1 1.9]
 [6.7 3.1 4.7 1.5]
 [7.3 2.9 6.3 1.8]
 [6.5 3.  5.2 2. ]
 [6.1 3.  4.

# **Encoding the Labels**

We must transform the column of classes, because we have a format 'str', and it is a multiclass situation. We must first convert the names of species into numerical values, then into vectors for the output of the neuron network.

In [10]:
# Transform name species into numerical values 
encoder = LabelEncoder()
encoder.fit(Y)
#converting to numerical values
Y = encoder.transform(Y)
#converting to vectors
Y = np_utils.to_categorical(Y)
print(Y)

# We have 3 classes : 
#0,0,1 : Class 1
#0,1,0 : Class 2
#1,0,0 : Class 3

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0.

# **Splitting data into train and test**

In [11]:
train_x, test_x, train_y, test_y = model_selection.train_test_split(X,Y,test_size = 0.1, random_state = 0)

# **Structuring neural network and training**

It's time to build our neural network. The dimension in input is the number of features of the dataframe (without the class to predict!).

We are on a multiclass classification situation, so the activation function for the last most suitable layer is "softmax", and "categorical_crossentropy" for the loss.

We have to do several tests to find the best architecture, but this one works pretty well

In [12]:
#using ANN
input_dim = len(iris.columns) - 1

model = Sequential()
model.add(Dense(8, input_dim = input_dim , activation = 'relu'))
model.add(Dense(10, activation = 'relu'))
model.add(Dense(10, activation = 'relu'))
model.add(Dense(10, activation = 'relu'))
model.add(Dense(3, activation = 'softmax'))

model.compile(loss = 'categorical_crossentropy' , optimizer = 'adam' , metrics = ['accuracy'] )

model.fit(train_x, train_y, epochs = 10, batch_size = 2)

scores = model.evaluate(test_x, test_y)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

Epoch 1/10
64/64 [==============================] - 0s 1ms/step - loss: 1.1311 - accuracy: 0.3622
Epoch 2/10
64/64 [==============================] - 0s 1ms/step - loss: 1.0121 - accuracy: 0.6299
Epoch 3/10
64/64 [==============================] - 0s 1ms/step - loss: 0.9273 - accuracy: 0.6457
Epoch 4/10
64/64 [==============================] - 0s 1ms/step - loss: 0.8029 - accuracy: 0.7638
Epoch 5/10
64/64 [==============================] - 0s 1ms/step - loss: 0.6592 - accuracy: 0.8504
Epoch 6/10
64/64 [==============================] - 0s 1ms/step - loss: 0.5220 - accuracy: 0.8583
Epoch 7/10
64/64 [==============================] - 0s 1ms/step - loss: 0.4422 - accuracy: 0.8425
Epoch 8/10
64/64 [==============================] - 0s 1ms/step - loss: 0.3922 - accuracy: 0.8425
Epoch 9/10
64/64 [==============================] - 0s 1ms/step - loss: 0.3558 - accuracy: 0.8819
Epoch 10/10
1/1 [==============================] - 0s 1ms/step - loss: 0.2083 - accuracy: 1.0000

accuracy: 100.00%


It is time to make predictions with the small sample removed from the base at the beginning. To train the neural network it was necessary to convert the species into vectors. So after the prediction it is necessary to carry out the opposite operation to recover the name of the associated species

In [13]:
predictions = model.predict_classes(prediction)
prediction_ = np.argmax(to_categorical(predictions), axis = 1)
prediction_ = encoder.inverse_transform(prediction_)

for i, j in zip(prediction_ , predict_species):
    print( " the nn predict {}, and the species to find is {}".format(i,j))


Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
 the nn predict Iris-setosa, and the species to find is Iris-setosa
 the nn predict Iris-virginica, and the species to find is Iris-virginica
 the nn predict Iris-versicolor, and the species to find is Iris-versicolor
 the nn predict Iris-versicolor, and the species to find is Iris-versicolor
 the nn predict Iris-versicolor, and the species to find is Iris-versicolor
 the nn predict Iris-setosa, and the species to find is Iris-setosa
 the nn predict Iris-virginica, and the species to find is Iris-virginica
 the nn predict Iris-setosa, and the species to find is Iris-setosa
